version: "2"

services:
  site:
    build:
      context: .
    image: nllevin/custom-drupal
    ports:
      - "8080:80"
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=hunter2
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data: